apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: limoneno-deploy-binding
  namespace: limoneno
subjects:
- kind: Group
  name: limoneno-deploy
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io